apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yuvraj-Sharma-2000/kubernetes.git
    targetRevision: main
    path: operators
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
